# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: MIT
name: ryzenadj
title: RyzenAdj (UNOFFICIAL)
base: core22
version: 0.0.1
#adopt-info: ryzenadj
summary: Adjust power management settings for Ryzen APUs
description: |
  Refer [the upstream project website](https://github.com/FlyGoat/RyzenAdj) for info on using this application.

  **Disclaimer:**

  This is NOT an official distribution of RyzenAdj, refer the
  snap's own issue tracker for support:

      Issues · 林博仁 Buo-ren Lin / Unofficial snap packaging for RyzenAdj · GitLab
      https://gitlab.com/brlin/ryzenadj-snap/-/issues

grade: stable
confinement: classic

parts:
  ryzenadj:
    source: https://github.com/FlyGoat/RyzenAdj.git
    source-tag: v0.15.0
    source-depth: 1
    plugin: cmake
    # Reference:
    #
    # Build Requirements | Build | FlyGoat/RyzenAdj: Adjust power management settings for Ryzen APUs
    # https://github.com/FlyGoat/RyzenAdj?tab=readme-ov-file#build-requirements
    build-packages:
      - gcc
      - g++
      - libpci-dev
    stage-packages:
      - libpci3
    build-attributes:
      - enable-patchelf

apps:
  ryzenadj:
    command: usr/local/bin/ryzenadj
    plugs:
      # Allow readwrite access to /dev/mem
      # https://snapcraft.io/docs/physical-memory-observe-interface
      - physical-memory-control

      # Allow readonly access to sysfs attributes of PCI devices
      - hardware-observe
