# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: MIT
name: ryzenadj
title: RyzenAdj (UNOFFICIAL)
base: core22
adopt-info: ryzenadj
summary: Adjust power management settings for Ryzen APUs
description: |
  Refer [the upstream project website](https://github.com/FlyGoat/RyzenAdj) for info on using this application.

  **Disclaimer:**

  This is NOT an official distribution of RyzenAdj, refer the
  snap's own issue tracker for support:

      Issues · 林博仁 Buo-ren Lin / Unofficial snap packaging for RyzenAdj · GitLab
      https://gitlab.com/brlin/ryzenadj-snap/-/issues

grade: stable
confinement: classic

parts:
  ryzenadj:
    source: https://github.com/FlyGoat/RyzenAdj.git
    source-tag: v0.15.0
    source-depth: 1
    override-pull: |
      printf 'Info: Running the default logic for the pull step...\n'
      if ! craftctl default; then
        printf \
          'Error: Unable to run the default logic for the pull step.\n' \
          1>&2
        exit 2
      fi

      printf 'Info: Detecting the version string of the main part...\n'
      if ! upstream_version_string_raw="$(
        git describe \
          --always \
          --tags \
          --dirty
        )"; then
        printf \
          'Error: Unable to detect the raw upstream version string of the main part.\n' \
          1>&2
        exit 2
      fi
      upstream_version_string="${upstream_version_string_raw#v}"
      printf \
        'Info: Upstream version string of the main part determined to be "%s".\n' \
        "${upstream_version_string}"

      printf 'Info: Determining the packaging version string...\n'
      if ! packaging_version_string="$(
        git -C "${CRAFT_PROJECT_DIR}" describe \
          --always \
          --abbrev=4
        )"; then
        printf \
          'Error: Unable to determine the packaging version string.\n' \
          1>&2
        exit 2
      fi
      printf \
        'Info: Packaging version string determined to be "%s".\n' \
        "${packaging_version_string}"

      printf 'Info: Determining the snap version string...\n'
      snap_version_string="${upstream_version_string}+s${packaging_version_string}"
      printf \
        'Info: Snap version string determined to be "%s".' \
        "${snap_version_string}"

      printf \
        'Info: Setting the version property of the snap metadata...\n'
      if ! craftctl set version="${snap_version_string}"; then
        printf \
          'Error: Unable to set the version property of the snap metadata.\n' \
          1>&2
        exit 2
      fi

      printf 'Info: Operation completed successfully.\n'

    plugin: cmake
    # Reference:
    #
    # Build Requirements | Build | FlyGoat/RyzenAdj: Adjust power management settings for Ryzen APUs
    # https://github.com/FlyGoat/RyzenAdj?tab=readme-ov-file#build-requirements
    build-packages:
      - gcc
      - g++
      - libpci-dev
    stage-packages:
      - libpci3
    build-attributes:
      - enable-patchelf

apps:
  ryzenadj:
    command: usr/local/bin/ryzenadj
    #plugs:
      # Allow readwrite access to /dev/mem
      # https://snapcraft.io/docs/physical-memory-observe-interface
      #- physical-memory-control

      # Allow readonly access to sysfs attributes of PCI devices
      #- hardware-observe
